#!/usr/bin/env bash
# 1 to 100 but with fizz, buzz and fizzbuzz

num=1
while [ $num -le 100 ]
do
if [ $((num % 15)) -eq 0 ]
then
echo "FizzBuzz"
elif [ $((num % 5)) -eq 0 ]
then
echo "Buzz"
elif [ $((num % 3)) -eq 0 ]
then
echo "Fizz"
else
echo $num
fi
((num++))
done
