#!/usr/bin/env bash
# Tells the story of passwd

while IFS= read -r line
do
IFS=: read -r username password id group idinfo home comman <<<"$line"
echo "The user $username is part of the $group gang, lives in $home and rides $comman. $id's place is protected by the passcode $password, more info about the user here: $idinfo"
done < "/etc/passwd"
