#!/usr/bin/env bash
# Shows the content of the current directory in list format

for file in *; do
if [[ -f "$file" && ! "$file" == .* ]]; then
filename=$(echo "$file" | cut -d '-' -f2-)
echo "$filename"
fi
done
