#!/usr/bin/env bash
# Bash script that uses signals and loops
echo $$ > /var/run/myscript.pid
while true; do
echo "To infinity and beyond"
sleep 2
done
trap 'echo "I hate the kill command" && rm /var/run/myscript.pid' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid' SIGQUIT
