#!/usr/bin/env bash
# Bash script that uses signals and loops
file=/var/run/myscript.pid
echo '$$' > $file
while true; do
echo "To infinity and beyond"
sleep 2
done
hatekill(){
	echo "I hate the kill command"
	rm $file
	exit 0
}
trap 'hatekill' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid' SIGQUIT
